FROM maven:3.9.6-amazoncorretto-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests -B

FROM amazoncorretto:17
WORKDIR /app
COPY --from=build /app/target/vinyl-exchange-0.0.1.jar app.jar
EXPOSE 10000
ENTRYPOINT ["java", "-Xmx350m", "-XX:MaxMetaspaceSize=128m", "-jar", "app.jar"]